Q1. **Get the positions where elements of a and b match**

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Output:

(array([1, 3, 5, 7]),)



In [58]:
# Write code for Q1 here
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

Q2. **Get all items between 5 and 10 from a.**

a = np.array([2, 6, 1, 9, 10, 3, 27])

In [14]:
# Write code for Q2 here
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
x=a[a>=5]
x
y=x[x<=10]
y

array([ 6,  9, 10])

Q3. **Swap columns 1 and 2 in the array arr.**

arr = np.arange(9).reshape(3,3)

In [19]:
# Write code for Q3 here
arr = np.arange(9).reshape(3,3)
arr[:,(0,1)]=arr[:,(1,0)]
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Q4. Reverse the rows of a 2D array arr.

arr = np.arange(9).reshape(3,3)

In [21]:
# Write code for Q4 here
arr = np.arange(9).reshape(3,3)
arr
arr[(0,2),:]=arr[(2,0),:]
arr

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Q5. Find the 5th and 95th percentile of iris's sepallength
Note - Find input code in the next cell

In [24]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength

# Write code for Q5 here


array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [23]:
np.percentile(sepallength,95)

7.254999999999998

In [25]:
np.percentile(sepallength,5)

4.6

Q6. Find the positions of NaN in the sepalLength numpy array

In [63]:
# This is the input of your question
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

sepalLength=iris_2d[:,0]
# This is the sepalLength
sepalLength

# Write your code here
# Hint - You can use the isNan() function.

array([5.1, nan, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, nan, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, nan, nan, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, nan, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, nan, 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, nan, 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [68]:
b=np.isnan(sepalLength)
np.where(b==True)

(array([  1,  10,  29,  30,  76,  83, 119]),)

Q7 .Replace all the null values with 0 in the above used sepalLength array

In [34]:
# Write your code here
a=np.isnan(sepalLength)
np.where(a==True,0,sepalLength)

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 0. , 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 0. , 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 0. , 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 0. , 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       0. , 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 0. , 6.9, 5.8,
       0. , 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

Q8. Find the 2nd largest value for the given array.

In [47]:
# Input
arr=np.random.randint(23,78, size=9).reshape(3,3)
arr

# Write your code here

array([[33, 71, 64],
       [52, 44, 53],
       [72, 36, 77]])

In [48]:
np.max(arr)
arr2=np.where(arr==np.max(arr),0,arr)
np.max(arr2)

72

Q9. From the array a, replace all values greater than 30 by 30 and less than 10 by 10.

In [54]:
# Input
arr=np.random.randint(1,78, size=9).reshape(3,3)
arr
# Write your code here

array([[ 9,  1, 71],
       [33, 49, 43],
       [76, 61, 72]])

In [55]:
arr4=np.where(arr>30,30,arr)
arr5=np.where(arr4<10,10,arr4)
arr5

array([[10, 10, 30],
       [30, 30, 30],
       [30, 30, 30]])

Q10. Drop all nan values from a 1D numpy array

In [60]:
arr=np.array([1,2,3,np.nan,5,6,7,np.nan])
arr

# Write code here


array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

In [61]:
arr=arr[~np.isnan(arr)]
arr

array([1., 2., 3., 5., 6., 7.])